services:
  auth:
    build: ./services/auth
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./services/auth/.env
    depends_on:
      - auth-db

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

volumes:
  auth-db-data: