services:
  marketing:
    build: ./services/marketing
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./services/marketing/.env
    depends_on:
      - marketing-db

  marketing-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - marketing-db-data:/var/lib/postgresql/data

volumes:
  marketing-db-data: